-- 98 more companies: 73 Y Combinator companies plus 25 well-known startups that post on Ashby, and a
-- Y Combinator tag so the app can show and filter them.
--
-- Why Y Combinator: the user asked to target YC-backed companies, "especially the prominent ones" -- whatever the
-- industry, most members will have heard of them. Source of the list: the public YC company directory (via the
-- yc-oss mirror, updated daily). Candidates were the active or public YC companies that YC flags as a top company
-- or that have 120+ people and a US presence (198); each one's public Greenhouse, Lever and Ashby boards were probed,
-- identity-checked, and run through the real relevance filter. 118 of the 198 have a public board; the rest (Rippling,
-- Deel, Retool, Whatnot, ...) use their own systems or non-guessable board names and are not here. Companies whose
-- name check was ambiguous (Tempo, Weave, a second "Apollo") were left out.
--
-- Identity: Greenhouse boards self-report company_name (the fetcher refuses a mismatching posting; config.board_name
-- holds the board's own spelling where it differs from the display name, e.g. "HackerRank Careers"). Lever and Ashby
-- postings carry no company name, so each was checked by hand that sampled posting descriptions name the company.
--
-- Tiers (per-company cap 25/15/10/5 for tiers 0-3): tier 1 = OpenAI, Ramp, Plaid, Notion, DoorDash, Kalshi, Perplexity, Cursor, Harvey,
-- Saronic, Oklo; tier 2 = YC top companies and other well-known names; tier 3 = the rest. Admins can change any of them.
--
-- company_yc also tags 20 companies that were already tracked (exact-name matches to the YC directory, reviewed
-- by hand: Airbnb, Stripe, Coinbase, Dropbox, Instacart, ...). Alloy, Guild and Prophet matched by name only
-- and are NOT YC companies, so they are not tagged.
create table if not exists company_yc (
  company_name text primary key,
  yc_batch text not null,       -- short form: W12, S19, X25
  yc_slug text,                 -- ycombinator.com/companies/<slug>
  created_at timestamptz not null default now()
);
comment on table company_yc is 'Companies backed by Y Combinator, keyed by the exact name jobs.company carries. Public YC directory data.';
alter table company_yc enable row level security;
create policy "company_yc_select_authenticated" on company_yc for select using (auth.role() = 'authenticated');
grant select on company_yc to authenticated;

insert into sources (name, type, authorization_status, api_available, rate_limits, attribution_required, storage_restrictions, redistribution_restricted, notes, config)
select
  v.company || ' (' || v.label || ')', 'employer_api', 'approved', true,
  'Polled with every other ' || v.platform_name || ' company on the batched schedule.',
  false,
  'Do not store full job description text -- same policy as every ' || v.platform_name || ' source in this app.',
  false,
  v.notes,
  v.config::jsonb
from (values
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'hackerrank', 'HackerRank', '{"platform": "greenhouse", "slug": "hackerrank", "company": "HackerRank", "board_name": "HackerRank Careers"}', 'Public Greenhouse board, slug "hackerrank". Y Combinator S11. 18/27 postings survived the relevance filter when added. Identity checked against the self-reported company_name ("HackerRank Careers").'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'singlestore', 'SingleStore', '{"platform": "greenhouse", "slug": "singlestore", "company": "SingleStore"}', 'Public Greenhouse board, slug "singlestore". Y Combinator W11. 29/40 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'rescale', 'Rescale', '{"platform": "ashby", "slug": "rescale", "company": "Rescale"}', 'Public Ashby board, slug "rescale". Y Combinator W12. 10/19 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'tremendous', 'Tremendous', '{"platform": "ashby", "slug": "tremendous", "company": "Tremendous"}', 'Public Ashby board, slug "tremendous". Y Combinator W11. 13/26 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'docker', 'Docker', '{"platform": "ashby", "slug": "docker", "company": "Docker"}', 'Public Ashby board, slug "docker". Y Combinator S10. 15/61 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'goatgroup', 'GOAT Group', '{"platform": "greenhouse", "slug": "goatgroup", "company": "GOAT Group"}', 'Public Greenhouse board, slug "goatgroup". Y Combinator W11. 7/9 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'mixpanel', 'Mixpanel', '{"platform": "greenhouse", "slug": "mixpanel", "company": "Mixpanel"}', 'Public Greenhouse board, slug "mixpanel". Y Combinator S09. 33/63 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'smartasset', 'SmartAsset', '{"platform": "greenhouse", "slug": "smartasset", "company": "SmartAsset"}', 'Public Greenhouse board, slug "smartasset". Y Combinator S12. 2/5 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'zapier', 'Zapier', '{"platform": "ashby", "slug": "zapier", "company": "Zapier"}', 'Public Ashby board, slug "zapier". Y Combinator S12. 7/11 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'fivetran', 'Fivetran', '{"platform": "greenhouse", "slug": "fivetran", "company": "Fivetran"}', 'Public Greenhouse board, slug "fivetran". Y Combinator W13. 60/181 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'benchling', 'Benchling', '{"platform": "ashby", "slug": "benchling", "company": "Benchling"}', 'Public Ashby board, slug "benchling". Y Combinator S12. 49/56 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'lob', 'Lob', '{"platform": "greenhouse", "slug": "lob", "company": "Lob"}', 'Public Greenhouse board, slug "lob". Y Combinator S13. 3/5 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'cambly', 'Cambly', '{"platform": "ashby", "slug": "cambly", "company": "Cambly"}', 'Public Ashby board, slug "cambly". Y Combinator W14. 3/4 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'scribdinc', 'Scribd', '{"platform": "ashby", "slug": "scribdinc", "company": "Scribd"}', 'Public Ashby board, slug "scribdinc". Y Combinator S06. 4/12 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'influxdata', 'InfluxData', '{"platform": "ashby", "slug": "influxdata", "company": "InfluxData"}', 'Public Ashby board, slug "influxdata". Y Combinator W13. 4/5 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'snapdocs', 'Snapdocs', '{"platform": "ashby", "slug": "snapdocs", "company": "Snapdocs"}', 'Public Ashby board, slug "snapdocs". Y Combinator W14. 3/4 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'shipbobinc', 'ShipBob', '{"platform": "greenhouse", "slug": "shipbobinc", "company": "ShipBob", "board_name": "ShipBob, Inc."}', 'Public Greenhouse board, slug "shipbobinc". Y Combinator S14. 36/57 postings survived the relevance filter when added. Identity checked against the self-reported company_name ("ShipBob, Inc.").'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'algolia', 'Algolia', '{"platform": "greenhouse", "slug": "algolia", "company": "Algolia"}', 'Public Greenhouse board, slug "algolia". Y Combinator W14. 24/38 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'oklo', 'Oklo', '{"platform": "greenhouse", "slug": "oklo", "company": "Oklo"}', 'Public Greenhouse board, slug "oklo". Y Combinator S14. 55/76 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'akidolabs', 'Akido Labs', '{"platform": "greenhouse", "slug": "akidolabs", "company": "Akido Labs", "board_name": "Akido"}', 'Public Greenhouse board, slug "akidolabs". Y Combinator W15. 14/23 postings survived the relevance filter when added. Identity checked against the self-reported company_name ("Akido").'),
  ('lever', 'Lever', 'Lever Postings API', 'mashgin', 'Mashgin', '{"platform": "lever", "slug": "mashgin", "company": "Mashgin"}', 'Public Lever board, slug "mashgin". Y Combinator W15. 8/12 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'goteleport', 'Teleport', '{"platform": "ashby", "slug": "goteleport", "company": "Teleport"}', 'Public Ashby board, slug "goteleport". Y Combinator S15. 7/24 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'instawork', 'Instawork', '{"platform": "greenhouse", "slug": "instawork", "company": "Instawork"}', 'Public Greenhouse board, slug "instawork". Y Combinator S15. 43/57 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('lever', 'Lever', 'Lever Postings API', 'rigetti', 'Rigetti Computing', '{"platform": "lever", "slug": "rigetti", "company": "Rigetti Computing"}', 'Public Lever board, slug "rigetti". Y Combinator S14. 5/16 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'qventus', 'Qventus', '{"platform": "greenhouse", "slug": "qventus", "company": "Qventus"}', 'Public Greenhouse board, slug "qventus". Y Combinator W15. 7/15 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('lever', 'Lever', 'Lever Postings API', 'superside', 'Superside', '{"platform": "lever", "slug": "superside", "company": "Superside"}', 'Public Lever board, slug "superside". Y Combinator W16. 9/15 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'ironcladhq', 'Ironclad', '{"platform": "ashby", "slug": "ironcladhq", "company": "Ironclad"}', 'Public Ashby board, slug "ironcladhq". Y Combinator S15. 13/32 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'lattice', 'Lattice', '{"platform": "greenhouse", "slug": "lattice", "company": "Lattice"}', 'Public Greenhouse board, slug "lattice". Y Combinator W16. 6/12 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'focalsystems', 'Focal Systems', '{"platform": "greenhouse", "slug": "focalsystems", "company": "Focal Systems"}', 'Public Greenhouse board, slug "focalsystems". Y Combinator W16. 12/36 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('lever', 'Lever', 'Lever Postings API', 'tovala', 'Tovala', '{"platform": "lever", "slug": "tovala", "company": "Tovala"}', 'Public Lever board, slug "tovala". Y Combinator W16. 6/10 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'sendbird', 'Sendbird', '{"platform": "greenhouse", "slug": "sendbird", "company": "Sendbird"}', 'Public Greenhouse board, slug "sendbird". Y Combinator W16. 7/8 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'billiontoone', 'BillionToOne', '{"platform": "greenhouse", "slug": "billiontoone", "company": "BillionToOne"}', 'Public Greenhouse board, slug "billiontoone". Y Combinator S17. 63/81 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'apolloio', 'Apollo.io', '{"platform": "greenhouse", "slug": "apolloio", "company": "Apollo.io"}', 'Public Greenhouse board, slug "apolloio". Y Combinator W16. 26/48 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'boom', 'Boom', '{"platform": "ashby", "slug": "boom", "company": "Boom"}', 'Public Ashby board, slug "boom". Y Combinator W16. 9/11 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'gecko-robotics', 'Gecko Robotics', '{"platform": "ashby", "slug": "gecko-robotics", "company": "Gecko Robotics"}', 'Public Ashby board, slug "gecko-robotics". Y Combinator W16. 23/23 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'saltsecurity', 'Salt Security', '{"platform": "greenhouse", "slug": "saltsecurity", "company": "Salt Security"}', 'Public Greenhouse board, slug "saltsecurity". Y Combinator W16. 11/13 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'vetcove', 'Vetcove', '{"platform": "ashby", "slug": "vetcove", "company": "Vetcove"}', 'Public Ashby board, slug "vetcove". Y Combinator S16. 14/27 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('lever', 'Lever', 'Lever Postings API', 'snappr', 'Snappr', '{"platform": "lever", "slug": "snappr", "company": "Snappr"}', 'Public Lever board, slug "snappr". Y Combinator W17. 14/17 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('lever', 'Lever', 'Lever Postings API', 'people-ai', 'People.ai', '{"platform": "lever", "slug": "people-ai", "company": "People.ai"}', 'Public Lever board, slug "people-ai". Y Combinator S16. 2/8 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'clipboard', 'Clipboard', '{"platform": "ashby", "slug": "clipboard", "company": "Clipboard"}', 'Public Ashby board, slug "clipboard". Y Combinator W17. 31/37 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'aclu', 'ACLU', '{"platform": "greenhouse", "slug": "aclu", "company": "ACLU", "board_name": "ACLU - National Office"}', 'Public Greenhouse board, slug "aclu". Y Combinator W17. 8/19 postings survived the relevance filter when added. Identity checked against the self-reported company_name ("ACLU - National Office").'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'maymobility', 'May Mobility', '{"platform": "greenhouse", "slug": "maymobility", "company": "May Mobility"}', 'Public Greenhouse board, slug "maymobility". Y Combinator S17. 20/40 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'modernhealth', 'Modern Health', '{"platform": "greenhouse", "slug": "modernhealth", "company": "Modern Health"}', 'Public Greenhouse board, slug "modernhealth". Y Combinator W18. 7/11 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'vanta', 'Vanta', '{"platform": "ashby", "slug": "vanta", "company": "Vanta"}', 'Public Ashby board, slug "vanta". Y Combinator W18. 36/84 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'pelago', 'Pelago', '{"platform": "greenhouse", "slug": "pelago", "company": "Pelago"}', 'Public Greenhouse board, slug "pelago". Y Combinator W18. 6/15 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('lever', 'Lever', 'Lever Postings API', 'captivateiq', 'CaptivateIQ', '{"platform": "lever", "slug": "captivateiq", "company": "CaptivateIQ"}', 'Public Lever board, slug "captivateiq". Y Combinator W18. 10/23 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'revenuecat', 'RevenueCat', '{"platform": "ashby", "slug": "revenuecat", "company": "RevenueCat"}', 'Public Ashby board, slug "revenuecat". Y Combinator S18. 4/20 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'moderntreasury', 'Modern Treasury', '{"platform": "ashby", "slug": "moderntreasury", "company": "Modern Treasury"}', 'Public Ashby board, slug "moderntreasury". Y Combinator S18. 7/9 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'observeai', 'Observe.AI', '{"platform": "greenhouse", "slug": "observeai", "company": "Observe.AI"}', 'Public Greenhouse board, slug "observeai". Y Combinator W18. 9/12 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'momentus', 'Momentus', '{"platform": "greenhouse", "slug": "momentus", "company": "Momentus", "board_name": "Momentus Space LLC"}', 'Public Greenhouse board, slug "momentus". Y Combinator S18. 6/8 postings survived the relevance filter when added. Identity checked against the self-reported company_name ("Momentus Space LLC").'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'postscript', 'Postscript', '{"platform": "greenhouse", "slug": "postscript", "company": "Postscript"}', 'Public Greenhouse board, slug "postscript". Y Combinator W19. 3/6 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'kalshi', 'Kalshi', '{"platform": "ashby", "slug": "kalshi", "company": "Kalshi"}', 'Public Ashby board, slug "kalshi". Y Combinator W19. 45/46 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'middesk', 'Middesk', '{"platform": "ashby", "slug": "middesk", "company": "Middesk"}', 'Public Ashby board, slug "middesk". Y Combinator W19. 16/17 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'nabis', 'Nabis', '{"platform": "greenhouse", "slug": "nabis", "company": "Nabis"}', 'Public Greenhouse board, slug "nabis". Y Combinator W19. 11/24 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'alpaca', 'Alpaca', '{"platform": "greenhouse", "slug": "alpaca", "company": "Alpaca"}', 'Public Greenhouse board, slug "alpaca". Y Combinator W19. 35/71 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'odeko', 'Odeko', '{"platform": "greenhouse", "slug": "odeko", "company": "Odeko"}', 'Public Greenhouse board, slug "odeko". Y Combinator S19. 9/21 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('lever', 'Lever', 'Lever Postings API', 'canarytechnologies', 'Canary Technologies', '{"platform": "lever", "slug": "canarytechnologies", "company": "Canary Technologies"}', 'Public Lever board, slug "canarytechnologies". Y Combinator S18. 26/38 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'ophelia', 'Ophelia', '{"platform": "greenhouse", "slug": "ophelia", "company": "Ophelia"}', 'Public Greenhouse board, slug "ophelia". Y Combinator W20. 7/16 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('lever', 'Lever', 'Lever Postings API', 'h1', 'H1', '{"platform": "lever", "slug": "h1", "company": "H1"}', 'Public Lever board, slug "h1". Y Combinator W20. 7/24 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'pairteam', 'Pair Team', '{"platform": "greenhouse", "slug": "pairteam", "company": "Pair Team"}', 'Public Greenhouse board, slug "pairteam". Y Combinator S19. 13/19 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'posthog', 'PostHog', '{"platform": "ashby", "slug": "posthog", "company": "PostHog"}', 'Public Ashby board, slug "posthog". Y Combinator W20. 8/8 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'zip', 'Zip', '{"platform": "ashby", "slug": "zip", "company": "Zip"}', 'Public Ashby board, slug "zip". Y Combinator S20. 74/124 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'supabase', 'Supabase', '{"platform": "ashby", "slug": "supabase", "company": "Supabase"}', 'Public Ashby board, slug "supabase". Y Combinator S20. 46/48 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'trm-labs', 'TRM Labs', '{"platform": "ashby", "slug": "trm-labs", "company": "TRM Labs"}', 'Public Ashby board, slug "trm-labs". Y Combinator S19. 51/112 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('lever', 'Lever', 'Lever Postings API', 'tryjeeves', 'Jeeves', '{"platform": "lever", "slug": "tryjeeves", "company": "Jeeves"}', 'Public Lever board, slug "tryjeeves". Y Combinator S20. 48/67 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'fieldguide', 'Fieldguide', '{"platform": "ashby", "slug": "fieldguide", "company": "Fieldguide"}', 'Public Ashby board, slug "fieldguide". Y Combinator S20. 23/46 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'gigs', 'Gigs', '{"platform": "ashby", "slug": "gigs", "company": "Gigs"}', 'Public Ashby board, slug "gigs". Y Combinator W21. 50/59 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'onebrief', 'Onebrief', '{"platform": "ashby", "slug": "onebrief", "company": "Onebrief"}', 'Public Ashby board, slug "onebrief". Y Combinator S21. 19/31 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'tennr', 'Tennr', '{"platform": "ashby", "slug": "tennr", "company": "Tennr"}', 'Public Ashby board, slug "tennr". Y Combinator W23. 15/27 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'marqvision', 'MarqVision', '{"platform": "greenhouse", "slug": "marqvision", "company": "MarqVision"}', 'Public Greenhouse board, slug "marqvision". Y Combinator S21. 9/16 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'candidhealth', 'Candid Health', '{"platform": "ashby", "slug": "candidhealth", "company": "Candid Health"}', 'Public Ashby board, slug "candidhealth". Y Combinator W20. 31/35 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'humaninterest', 'Human Interest', '{"platform": "greenhouse", "slug": "humaninterest", "company": "Human Interest"}', 'Public Greenhouse board, slug "humaninterest". Y Combinator S15. 58/72 postings survived the relevance filter when added. Identity checked against the self-reported company_name.'),
  ('greenhouse', 'Greenhouse', 'Greenhouse Job Board API', 'doordashusa', 'DoorDash', '{"platform": "greenhouse", "slug": "doordashusa", "company": "DoorDash", "board_name": "DoorDash USA"}', 'Public Greenhouse board, slug "doordashusa". Y Combinator S13. 458 postings on the board when added. Identity checked against the self-reported company_name ("DoorDash USA").'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'openai', 'OpenAI', '{"platform": "ashby", "slug": "openai", "company": "OpenAI"}', 'Public Ashby board, slug "openai". 730/830 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'ramp', 'Ramp', '{"platform": "ashby", "slug": "ramp", "company": "Ramp"}', 'Public Ashby board, slug "ramp". 123/157 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'notion', 'Notion', '{"platform": "ashby", "slug": "notion", "company": "Notion"}', 'Public Ashby board, slug "notion". 128/137 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'plaid', 'Plaid', '{"platform": "ashby", "slug": "plaid", "company": "Plaid"}', 'Public Ashby board, slug "plaid". 85/119 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'harvey', 'Harvey', '{"platform": "ashby", "slug": "harvey", "company": "Harvey"}', 'Public Ashby board, slug "harvey". 189/326 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'perplexity', 'Perplexity', '{"platform": "ashby", "slug": "perplexity", "company": "Perplexity"}', 'Public Ashby board, slug "perplexity". 69/127 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'cursor', 'Cursor', '{"platform": "ashby", "slug": "cursor", "company": "Cursor"}', 'Public Ashby board, slug "cursor". 116/132 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'cohere', 'Cohere', '{"platform": "ashby", "slug": "cohere", "company": "Cohere"}', 'Public Ashby board, slug "cohere". 85/136 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'saronic', 'Saronic', '{"platform": "ashby", "slug": "saronic", "company": "Saronic"}', 'Public Ashby board, slug "saronic". 148/207 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'skydio', 'Skydio', '{"platform": "ashby", "slug": "skydio", "company": "Skydio"}', 'Public Ashby board, slug "skydio". 84/144 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'whoop', 'Whoop', '{"platform": "ashby", "slug": "whoop", "company": "Whoop"}', 'Public Ashby board, slug "whoop". 69/154 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'away', 'Away', '{"platform": "ashby", "slug": "away", "company": "Away"}', 'Public Ashby board, slug "away". 30/33 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'formenergy', 'Form Energy', '{"platform": "ashby", "slug": "formenergy", "company": "Form Energy"}', 'Public Ashby board, slug "formenergy". 60/203 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'helion', 'Helion', '{"platform": "ashby", "slug": "helion", "company": "Helion"}', 'Public Ashby board, slug "helion". 28/69 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'headway', 'Headway', '{"platform": "ashby", "slug": "headway", "company": "Headway"}', 'Public Ashby board, slug "headway". 22/88 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'lemonade', 'Lemonade', '{"platform": "ashby", "slug": "lemonade", "company": "Lemonade"}', 'Public Ashby board, slug "lemonade". 14/41 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'circle', 'Circle', '{"platform": "ashby", "slug": "circle", "company": "Circle"}', 'Public Ashby board, slug "circle". 17/41 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'paxos', 'Paxos', '{"platform": "ashby", "slug": "paxos", "company": "Paxos"}', 'Public Ashby board, slug "paxos". 9/14 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'linear', 'Linear', '{"platform": "ashby", "slug": "linear", "company": "Linear"}', 'Public Ashby board, slug "linear". 23/30 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'miro', 'Miro', '{"platform": "ashby", "slug": "miro", "company": "Miro"}', 'Public Ashby board, slug "miro". 24/28 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'strava', 'Strava', '{"platform": "ashby", "slug": "strava", "company": "Strava"}', 'Public Ashby board, slug "strava". 12/30 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'patreon', 'Patreon', '{"platform": "ashby", "slug": "patreon", "company": "Patreon"}', 'Public Ashby board, slug "patreon". 7/16 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'poshmark', 'Poshmark', '{"platform": "ashby", "slug": "poshmark", "company": "Poshmark"}', 'Public Ashby board, slug "poshmark". 13/30 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'substack', 'Substack', '{"platform": "ashby", "slug": "substack", "company": "Substack"}', 'Public Ashby board, slug "substack". 12/17 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.'),
  ('ashby', 'Ashby', 'Ashby Job Posting API', 'acorns', 'Acorns', '{"platform": "ashby", "slug": "acorns", "company": "Acorns"}', 'Public Ashby board, slug "acorns". 4/9 postings survived the relevance filter when added. Identity checked: sampled posting descriptions name the company.')
) as v(platform, platform_name, label, slug, company, config, notes)
where not exists (select 1 from sources s where s.config->>'platform' = v.platform and s.config->>'slug' = v.slug);

insert into company_tiers (company_name, tier, note) values
  ('HackerRank', 2, 'YC S11'),
  ('SingleStore', 2, 'YC W11'),
  ('Rescale', 3, 'YC W12'),
  ('Tremendous', 3, 'YC W11'),
  ('Docker', 2, 'YC S10'),
  ('GOAT Group', 2, 'YC W11'),
  ('Mixpanel', 2, 'YC S09'),
  ('SmartAsset', 2, 'YC S12'),
  ('Zapier', 2, 'YC S12'),
  ('Fivetran', 2, 'YC W13'),
  ('Benchling', 2, 'YC S12'),
  ('Lob', 3, 'YC S13'),
  ('Cambly', 3, 'YC W14'),
  ('Scribd', 2, 'YC S06'),
  ('InfluxData', 3, 'YC W13'),
  ('Snapdocs', 3, 'YC W14'),
  ('ShipBob', 2, 'YC S14'),
  ('Algolia', 2, 'YC W14'),
  ('Oklo', 1, 'YC S14'),
  ('Akido Labs', 3, 'YC W15'),
  ('Mashgin', 3, 'YC W15'),
  ('Teleport', 3, 'YC S15'),
  ('Instawork', 2, 'YC S15'),
  ('Rigetti Computing', 2, 'YC S14'),
  ('Qventus', 3, 'YC W15'),
  ('Superside', 3, 'YC W16'),
  ('Ironclad', 2, 'YC S15'),
  ('Lattice', 3, 'YC W16'),
  ('Focal Systems', 3, 'YC W16'),
  ('Tovala', 3, 'YC W16'),
  ('Sendbird', 3, 'YC W16'),
  ('BillionToOne', 3, 'YC S17'),
  ('Apollo.io', 2, 'YC W16'),
  ('Boom', 2, 'YC W16'),
  ('Gecko Robotics', 2, 'YC W16'),
  ('Salt Security', 3, 'YC W16'),
  ('Vetcove', 3, 'YC S16'),
  ('Snappr', 3, 'YC W17'),
  ('People.ai', 3, 'YC S16'),
  ('Clipboard', 2, 'YC W17'),
  ('ACLU', 3, 'YC W17'),
  ('May Mobility', 3, 'YC S17'),
  ('Modern Health', 3, 'YC W18'),
  ('Vanta', 2, 'YC W18'),
  ('Pelago', 3, 'YC W18'),
  ('CaptivateIQ', 3, 'YC W18'),
  ('RevenueCat', 3, 'YC S18'),
  ('Modern Treasury', 3, 'YC S18'),
  ('Observe.AI', 3, 'YC W18'),
  ('Momentus', 2, 'YC S18'),
  ('Postscript', 3, 'YC W19'),
  ('Kalshi', 1, 'YC W19'),
  ('Middesk', 2, 'YC W19'),
  ('Nabis', 3, 'YC W19'),
  ('Alpaca', 2, 'YC W19'),
  ('Odeko', 2, 'YC S19'),
  ('Canary Technologies', 2, 'YC S18'),
  ('Ophelia', 3, 'YC W20'),
  ('H1', 3, 'YC W20'),
  ('Pair Team', 3, 'YC S19'),
  ('PostHog', 2, 'YC W20'),
  ('Zip', 2, 'YC S20'),
  ('Supabase', 2, 'YC S20'),
  ('TRM Labs', 2, 'YC S19'),
  ('Jeeves', 2, 'YC S20'),
  ('Fieldguide', 3, 'YC S20'),
  ('Gigs', 2, 'YC W21'),
  ('Onebrief', 3, 'YC S21'),
  ('Tennr', 3, 'YC W23'),
  ('MarqVision', 3, 'YC S21'),
  ('Candid Health', 2, 'YC W20'),
  ('Human Interest', 2, 'YC S15'),
  ('DoorDash', 1, 'YC S13'),
  ('OpenAI', 1, 'added with the Ashby adapter'),
  ('Ramp', 1, 'added with the Ashby adapter'),
  ('Notion', 1, 'added with the Ashby adapter'),
  ('Plaid', 1, 'added with the Ashby adapter'),
  ('Harvey', 1, 'added with the Ashby adapter'),
  ('Perplexity', 1, 'added with the Ashby adapter'),
  ('Cursor', 1, 'added with the Ashby adapter'),
  ('Cohere', 2, 'added with the Ashby adapter'),
  ('Saronic', 1, 'added with the Ashby adapter'),
  ('Skydio', 2, 'added with the Ashby adapter'),
  ('Whoop', 2, 'added with the Ashby adapter'),
  ('Away', 2, 'added with the Ashby adapter'),
  ('Form Energy', 2, 'added with the Ashby adapter'),
  ('Helion', 2, 'added with the Ashby adapter'),
  ('Headway', 2, 'added with the Ashby adapter'),
  ('Lemonade', 2, 'added with the Ashby adapter'),
  ('Circle', 2, 'added with the Ashby adapter'),
  ('Paxos', 3, 'added with the Ashby adapter'),
  ('Linear', 2, 'added with the Ashby adapter'),
  ('Miro', 2, 'added with the Ashby adapter'),
  ('Strava', 2, 'added with the Ashby adapter'),
  ('Patreon', 3, 'added with the Ashby adapter'),
  ('Poshmark', 2, 'added with the Ashby adapter'),
  ('Substack', 3, 'added with the Ashby adapter'),
  ('Acorns', 3, 'added with the Ashby adapter')
on conflict (company_name) do nothing;

insert into company_yc (company_name, yc_batch, yc_slug) values
  ('HackerRank', 'S11', 'hackerrank'),
  ('SingleStore', 'W11', 'singlestore'),
  ('Rescale', 'W12', 'rescale'),
  ('Tremendous', 'W11', 'tremendous'),
  ('Docker', 'S10', 'docker'),
  ('GOAT Group', 'W11', 'goat-group'),
  ('Mixpanel', 'S09', 'mixpanel'),
  ('SmartAsset', 'S12', 'smartasset'),
  ('Zapier', 'S12', 'zapier'),
  ('Fivetran', 'W13', 'fivetran'),
  ('Benchling', 'S12', 'benchling'),
  ('Lob', 'S13', 'lob'),
  ('Cambly', 'W14', 'cambly'),
  ('Scribd', 'S06', 'scribd'),
  ('InfluxData', 'W13', 'influxdata'),
  ('Snapdocs', 'W14', 'snapdocs'),
  ('ShipBob', 'S14', 'shipbob'),
  ('Algolia', 'W14', 'algolia'),
  ('Oklo', 'S14', 'oklo'),
  ('Akido Labs', 'W15', 'akido-labs'),
  ('Mashgin', 'W15', 'mashgin'),
  ('Teleport', 'S15', 'teleport'),
  ('Instawork', 'S15', 'instawork'),
  ('Rigetti Computing', 'S14', 'rigetti-computing'),
  ('Qventus', 'W15', 'qventus'),
  ('Superside', 'W16', 'superside'),
  ('Ironclad', 'S15', 'ironclad'),
  ('Lattice', 'W16', 'lattice'),
  ('Focal Systems', 'W16', 'focal-systems'),
  ('Tovala', 'W16', 'tovala'),
  ('Sendbird', 'W16', 'sendbird'),
  ('BillionToOne', 'S17', 'billiontoone'),
  ('Apollo.io', 'W16', 'apollo-io'),
  ('Boom', 'W16', 'boom'),
  ('Gecko Robotics', 'W16', 'gecko-robotics'),
  ('Salt Security', 'W16', 'salt-security'),
  ('Vetcove', 'S16', 'vetcove'),
  ('Snappr', 'W17', 'snappr'),
  ('People.ai', 'S16', 'people-ai'),
  ('Clipboard', 'W17', 'clipboard'),
  ('ACLU', 'W17', 'aclu'),
  ('May Mobility', 'S17', 'may-mobility'),
  ('Modern Health', 'W18', 'modern-health'),
  ('Vanta', 'W18', 'vanta'),
  ('Pelago', 'W18', 'pelago'),
  ('CaptivateIQ', 'W18', 'captivateiq'),
  ('RevenueCat', 'S18', 'revenuecat'),
  ('Modern Treasury', 'S18', 'modern-treasury'),
  ('Observe.AI', 'W18', 'observe-ai'),
  ('Momentus', 'S18', 'momentus'),
  ('Postscript', 'W19', 'postscript'),
  ('Kalshi', 'W19', 'kalshi'),
  ('Middesk', 'W19', 'middesk'),
  ('Nabis', 'W19', 'nabis'),
  ('Alpaca', 'W19', 'alpaca'),
  ('Odeko', 'S19', 'odeko'),
  ('Canary Technologies', 'S18', 'canary-technologies'),
  ('Ophelia', 'W20', 'ophelia'),
  ('H1', 'W20', 'h1'),
  ('Pair Team', 'S19', 'pair-team'),
  ('PostHog', 'W20', 'posthog'),
  ('Zip', 'S20', 'zip'),
  ('Supabase', 'S20', 'supabase'),
  ('TRM Labs', 'S19', 'trm-labs'),
  ('Jeeves', 'S20', 'jeeves'),
  ('Fieldguide', 'S20', 'fieldguide'),
  ('Gigs', 'W21', 'gigs'),
  ('Onebrief', 'S21', 'onebrief'),
  ('Tennr', 'W23', 'tennr'),
  ('MarqVision', 'S21', 'marqvision'),
  ('Candid Health', 'W20', 'candid-health'),
  ('Human Interest', 'S15', 'human-interest'),
  ('DoorDash', 'S13', 'doordash'),
  ('Airbnb', 'W09', 'airbnb'),
  ('Amplitude', 'W12', 'amplitude'),
  ('Astranis', 'W16', 'astranis'),
  ('Brex', 'W17', 'brex'),
  ('Checkr', 'S14', 'checkr'),
  ('Coinbase', 'S12', 'coinbase'),
  ('Dropbox', 'S07', 'dropbox'),
  ('Faire', 'W17', 'faire'),
  ('Flexport', 'W14', 'flexport'),
  ('Ginkgo Bioworks Inc.', 'S14', 'ginkgo-bioworks'),
  ('GitLab', 'W15', 'gitlab'),
  ('Gusto, Inc.', 'W12', 'gusto'),
  ('Instacart', 'S12', 'instacart'),
  ('PagerDuty', 'S10', 'pagerduty'),
  ('Reddit', 'S05', 'reddit'),
  ('Relativity Space', 'W16', 'relativity-space'),
  ('Scale AI', 'S16', 'scale-ai'),
  ('Stripe', 'S09', 'stripe'),
  ('Twitch', 'W07', 'twitch'),
  ('Webflow', 'S13', 'webflow')
on conflict (company_name) do nothing;

-- Capacity. Greenhouse is fetched in batches (stalest first) and every enabled company has to come round inside the
-- 26-hour coverage window: 14 per 2 hours is 168 a day, which is below the ~210 Greenhouse companies there now.
-- 20 per 2 hours is 240 a day. Ashby runs hourly in batches of 8 (192 a day) rather than 14 every 2 hours: a first
-- fetch of a big board inserts up to 150 jobs, and smaller batches keep one invocation well inside the Edge
-- Function limit (the all-at-once Greenhouse run was killed by it).
select cron.unschedule('fetch-greenhouse-companies-batch');
select cron.schedule(
  'fetch-greenhouse-companies-batch',
  '17 */2 * * *',
  $$
  select net.http_post(
    url := 'https://cfwbtzajnaodgqilgkqn.supabase.co/functions/v1/fetch-greenhouse-companies',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmd2J0emFqbmFvZGdxaWxna3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg5MTk3NTQsImV4cCI6MjEwNDQ5NTc1NH0.pMdJ5vEZXrBaVQqkqXJycjGVOF116hTvusYUsagSc7w',
      'X-Cron-Secret', (select decrypted_secret from vault.decrypted_secrets where name = 'cron_secret')
    ),
    body := '{"batch": 20}'::jsonb
  );
  $$
);

select cron.unschedule('fetch-ashby-companies-batch');
select cron.schedule(
  'fetch-ashby-companies-batch',
  '47 * * * *',
  $$
  select net.http_post(
    url := 'https://cfwbtzajnaodgqilgkqn.supabase.co/functions/v1/fetch-ashby-companies',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmd2J0emFqbmFvZGdxaWxna3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg5MTk3NTQsImV4cCI6MjEwNDQ5NTc1NH0.pMdJ5vEZXrBaVQqkqXJycjGVOF116hTvusYUsagSc7w',
      'X-Cron-Secret', (select decrypted_secret from vault.decrypted_secrets where name = 'cron_secret')
    ),
    body := '{"batch": 8}'::jsonb
  );
  $$
);
